"""add rating

Revision ID: 3fd1c0dc3e6d
Revises: ee7e96fa32c9
Create Date: 2023-07-27 12:20:19.486025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd1c0dc3e6d'
down_revision = 'ee7e96fa32c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_score_company',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_score_company_id'), 'average_score_company', ['id'], unique=False)
    op.create_table('average_score_global',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user')
    )
    op.create_index(op.f('ix_average_score_global_id'), 'average_score_global', ['id'], unique=False)
    op.create_table('resul_test',
    sa.Column('count_correct_answers', sa.Integer(), nullable=False),
    sa.Column('count_questions', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.Column('id_quiz', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['id_quiz'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resul_test_id'), 'resul_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resul_test_id'), table_name='resul_test')
    op.drop_table('resul_test')
    op.drop_index(op.f('ix_average_score_global_id'), table_name='average_score_global')
    op.drop_table('average_score_global')
    op.drop_index(op.f('ix_average_score_company_id'), table_name='average_score_company')
    op.drop_table('average_score_company')
    # ### end Alembic commands ###
