"""add hide company

Revision ID: bf4db3d8ca73
Revises: a2ad8cbd362f
Create Date: 2023-07-19 15:00:32.097013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4db3d8ca73'
down_revision = 'a2ad8cbd362f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('сompany', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('сompany', 'is_hidden')
    # ### end Alembic commands ###
